-- Profiles table for user metadata
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  worker_id TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Onboarding data
CREATE TABLE public.onboarding_data (
  user_id UUID REFERENCES public.profiles ON DELETE CASCADE PRIMARY KEY,
  data JSONB,
  completed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Wellness metrics (historical data)
CREATE TABLE public.wellness_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles ON DELETE CASCADE,
  heart_rate INTEGER,
  sleep_hours FLOAT,
  steps INTEGER,
  score INTEGER,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Anonymous messages/reports
CREATE TABLE public.anonymous_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wellness_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anonymous_messages ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage their own onboarding" ON public.onboarding_data FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own metrics" ON public.wellness_metrics FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own metrics" ON public.wellness_metrics FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Anyone can insert anonymous messages" ON public.anonymous_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view anonymous messages" ON public.anonymous_messages FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Active Alerts for extreme pilot fatigue / flight risk
CREATE TABLE public.active_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles ON DELETE CASCADE,
  severity TEXT DEFAULT 'warning' CHECK (severity IN ('warning', 'critical')),
  message TEXT NOT NULL,
  rule_triggered TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.active_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own alerts" ON public.active_alerts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own alerts" ON public.active_alerts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all alerts" ON public.active_alerts FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Automatic compliance alerting trigger on wellness metrics insertion
CREATE OR REPLACE FUNCTION public.handle_wellness_metrics_insert()
RETURNS TRIGGER AS $$
DECLARE
  compliance_framework TEXT;
  min_sleep_required FLOAT;
BEGIN
  -- Fetch compliance framework from onboarding_data if it exists
  SELECT COALESCE(data->>'compliance', 'UCAA')
  INTO compliance_framework
  FROM public.onboarding_data
  WHERE user_id = new.user_id;

  IF compliance_framework IS NULL THEN
    compliance_framework := 'UCAA';
  END IF;

  min_sleep_required := CASE WHEN compliance_framework = 'FAA' THEN 8.0 ELSE 7.0 END;

  IF new.sleep_hours < min_sleep_required THEN
    INSERT INTO public.active_alerts (user_id, severity, message, rule_triggered)
    VALUES (
      new.user_id,
      CASE WHEN new.score < 40 THEN 'critical' ELSE 'warning' END,
      'Insufficient rest detected under ' || compliance_framework || ' rules. Pilot slept ' || ROUND(new.sleep_hours::numeric, 1) || ' hrs (Required: ' || min_sleep_required || ' hrs).',
      compliance_framework || '_SLEEP_MINIMUM'
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_wellness_metrics_inserted
  AFTER INSERT ON public.wellness_metrics
  FOR EACH ROW EXECUTE PROCEDURE public.handle_wellness_metrics_insert();

-- Function to handle new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, role)
  VALUES (new.id, new.raw_user_meta_data->>'name', COALESCE(new.raw_user_meta_data->>'role', 'user'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
