-- Profiles table for user metadata
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  worker_id TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Onboarding data
CREATE TABLE public.onboarding_data (
  user_id UUID REFERENCES public.profiles ON DELETE CASCADE PRIMARY KEY,
  data JSONB,
  completed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Wellness metrics (historical data)
CREATE TABLE public.wellness_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles ON DELETE CASCADE,
  heart_rate INTEGER,
  sleep_hours FLOAT,
  steps INTEGER,
  score INTEGER,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Anonymous messages/reports
CREATE TABLE public.anonymous_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wellness_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anonymous_messages ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage their own onboarding" ON public.onboarding_data FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own metrics" ON public.wellness_metrics FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own metrics" ON public.wellness_metrics FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Anyone can insert anonymous messages" ON public.anonymous_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view anonymous messages" ON public.anonymous_messages FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Function to handle new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, role)
  VALUES (new.id, new.raw_user_meta_data->>'name', COALESCE(new.raw_user_meta_data->>'role', 'user'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
