import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ReportService {
  Future<void> generateAndPrintReport(Map<String, dynamic> data) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(level: 0, text: 'AeroMind Weekly Wellness Report'),
              pw.SizedBox(height: 20),
              pw.Text('Wellness Score: ${data['score']}/100'),
              pw.Text('Average Heart Rate: ${data['heartRate']} bpm'),
              pw.Text('Sleep Hours (24h): ${data['sleepHours'].toStringAsFixed(1)} h'),
              pw.Text('Steps: ${data['steps']}'),
              pw.SizedBox(height: 20),
              pw.Text('Status: ${data['score'] > 70 ? "FIT TO FLY" : "REST RECOMMENDED"}'),
              pw.SizedBox(height: 40),
              pw.Footer(title: pw.Text('Generated by AeroMind Wellness Intelligence')),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
